service: RestaurantReviews

plugins:
  modules:
    - serverless-cf-vars
    - serverless-appsync-plugin
    - aws-amplify-serverless-plugin

provider:
  name: aws
  region: ${opt:region, "us-east-1"}
  runtime: nodejs8.10
  stage: ${opt:stage, "dev"}

functions:
  dynamodbstream:
    handler: elasticsearch.lambda_handler
    name: ${self:custom.api}-dynamodb_stream_handler
    description: Stream data from DynamoDB to ElasticSearch
    runtime: python3.6
    memorySize: 128
    role: ElasticSearchStreamingLambdaIAMRole
    environment:
      ES_ENDPOINT: { Fn::GetAtt: [ ElasticSearchDomain, DomainEndpoint ]}
      ES_INDEX: ${self:custom.api}
      DEBUG: 1
    events:
      - stream:
          type: dynamodb
          arn: { Fn::GetAtt: [ DynamoDBTable, StreamArn ]}
  postdeployment:
    handler: elasticsearch.postdeployment_handler
    name: ${self:custom.api}-postdeployment_handler
    description: Update resources post-deployment
    runtime: python3.6
    memorySize: 128
    role: ElasticSearchStreamingLambdaIAMRole
    environment:
      ES_ENDPOINT: { Fn::GetAtt: [ ElasticSearchDomain, DomainEndpoint ]}
      ES_INDEX: ${self:custom.api}
      DEBUG: 1
  profilePictureResolver:
    handler: graphql.profilePictureResolver
    name: ${self:custom.api}-profilePictureResolver
    description: AppSync Resolver for User.profilePicture
    runtime: nodejs8.10
    role: AWSAppSyncS3LambdaIAMRole
    environment:
      S3_BUCKET: { Fn::GetAtt: [ FileStorage, Arn ]}
      S3_URL: { Fn::GetAtt: [ FileStorage, WebsiteURL ]}


custom:
  # The base name of the API for resource generation - can't include dashes
  # [a-zA-Z0-9]+ only
  api: ${self:provider.stage}RestaurantReviews
  # ES Domain, must match [a-z][a-z0-9\-]+
  es_domain: ${self:provider.stage}-restaurant-reviews
  # The number of instances to launch into the ElasticSearch domain
  es_instanceCount: 1
  # The type of instance to launch into the ElasticSearch domain
  es_instanceType: "t2.small.elasticsearch"
  # The size in GB of the EBS volumes that contain the data
  es_ebsVolumeGB: 20
  # The number of read IOPS the DynamoDB table should support.
  ddb_readIOPS: 5
  # The number of write IOPS the DynamoDB table should support.
  ddb_writeIOPS: 5

  # AWS Amplify configuration
  amplify:
    - filename: ../mobile-app/src/amplify/aws-exports.js
      type: javascript
      appClient: ReactNativeUserPoolClient

  # AWS AppSync GraphQL configuration
  appSync:
    name: ${self:custom.api}
    authenticationType: AWS_IAM
    logConfig:
      loggingRoleArn: { Fn::GetAtt: [ AppSyncLoggingServiceRole, Arn ]}
      level: ALL
    schema: ./schema.graphql
    dataSources:
      - type: AMAZON_DYNAMODB
        name: DynamoDB
        config:
          tableName: { Ref: DynamoDBTable }
          iamRoleStatements:
            - Effect: Allow
              Action:
                - "dynamodb:PutItem"
                - "dynamodb:GetItem"
                - "dynamodb:Query"
                - "dynamodb:BatchGetItem"
              Resource:
                - { Fn::GetAtt: [ DynamoDBTable, Arn ]}
                - { Fn::Join: [ "/", [{ Fn::GetAtt: [ DynamoDBTable, Arn ]}, "*" ]]}
      - type: AMAZON_ELASTICSEARCH
        name: ElasticSearch
        config:
          endpoint: { Fn::Join: [ "", [ "https://", { Fn::GetAtt: [ ElasticSearchDomain, DomainEndpoint ]} ]]}
          iamRoleStatements:
            - Effect: Allow
              Action:
                - "es:ESHttpGet"
              Resource:
                - { Fn::Join: [ "", [ { Fn::GetAtt: [ ElasticSearchDomain, DomainArn ]}, "/*" ]]}
      - type: AWS_LAMBDA
        name: ProfilePictures
        description: Lambda function for the ProfilePictures
        config:
          lambdaFunctionArn: { Fn::GetAtt: [ ProfilePictureResolverLambdaFunction, Arn ]}
          iamRoleStatements:
            - Effect: Allow
              Action:
                - "lambda:invokeFunction"
              Resource:
                - { Fn::GetAtt: [ ProfilePictureResolverLambdaFunction, Arn ]}
    mappingTemplates:
      - type: Mutation
        field: addLocation
        dataSource: DynamoDB
        request: Mutation-addLocation-request.vtl
        response: common-response.vtl
      - type: Mutation
        field: addReview
        dataSource: DynamoDB
        request: Mutation-addReview-request.vtl
        response: common-response.vtl
      - type: Mutation
        field: markFavorite
        request: Mutation-markFavorite-request.vtl
        response: common-response.vtl
        kind: PIPELINE
        functions:
          - getLocation
          - storeFavorite
      - type: Mutation
        field: updateUser
        dataSource: DynamoDB
        request: Mutation-updateUser-request.vtl
        response: common-response.vtl
      - type: Query
        field: me
        request: Query-me-request.vtl
        response: common-response.vtl
        kind: PIPELINE
        functions:
          - getUserById
          - getProfilePictureForId
      - type: Query
        field: getLocation
        dataSource: DynamoDB
        request: Query-getLocation-request.vtl
        response: common-response.vtl
      - type: Query
        field: findLocation
        dataSource: ElasticSearch
        request: Query-findLocation-request.vtl
        response: Query-findLocation-response.vtl
      - type: Location
        field: averageRating
        dataSource: ElasticSearch
        request: Location-averageRating-request.vtl
        response: Location-averageRating-response.vtl
      - type: Location
        field: favoriteCount
        dataSource: ElasticSearch
        request: Location-favoriteCount-request.vtl
        response: count-response.vtl
      - type: Location
        field: reviews
        dataSource: DynamoDB
        request: Location-reviews-request.vtl
        response: dynamodb-paged-response.vtl
      - type: Review
        field: user
        request: Review-user-request.vtl
        response: common-response.vtl
        kind: PIPELINE
        functions:
          - getUserById
          - getProfilePictureForId
      - type: Review
        field: location
        dataSource: DynamoDB
        request: Review-location-request.vtl
        response: common-response.vtl
      - type: User
        field: locations
        dataSource: ElasticSearch
        request: User-locations-request.vtl
        response: elasticsearch-paged-response.vtl
      - type: User
        field: reviews
        dataSource: ElasticSearch
        request: User-reviews-request.vtl
        response: elasticsearch-paged-response.vtl
      - type: User
        field: favorites
        request: User-favorites-request.vtl
        response: common-response.vtl
        kind: PIPELINE
        functions:
          - getFavorites
          - getLocationForList
    functionConfigurations:
      - dataSource: DynamoDB
        name: getLocation
        request: Function-getLocation-request.vtl
        response: Function-getLocation-response.vtl
      - dataSource: DynamoDB
        name: storeFavorite
        request: Function-storeFavorite-request.vtl
        response: Function-storeFavorite-response.vtl
      - dataSource: ElasticSearch
        name: getFavorites
        request: Function-getFavorites-request.vtl
        response: Function-getFavorites-response.vtl
      - dataSource: DynamoDB
        name: getLocationForList
        request: Function-getLocationForList-request.vtl
        response: Function-getLocationForList-response.vtl
      - dataSource: DynamoDB
        name: getUserById
        request: Function-getUserById-request.vtl
        response: Function-getUserById-response.vtl
      - dataSource: ProfilePictures
        name: getProfilePictureForId
        request: Function-getProfilePictureForId-request.vtl
        response: Function-getProfilePictureForId-response.vtl

resources:
  Resources:
    # -------------------------------------------------------------------------
    # BEGIN: AUTHENTICATION
    # -------------------------------------------------------------------------
    CognitoUserPoolUsers:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:custom.api}
        Schema:
          - Name: email
            Required: true
            Mutable: true
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireLowercase: false
            RequireUppercase: false
            RequireNumbers: false
            RequireSymbols: false
        AutoVerifiedAttributes: [ "email" ]
        MfaConfiguration: OFF

    ReactNativeUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:custom.api}-react-native
        GenerateSecret: true
        UserPoolId: { Ref: CognitoUserPoolUsers }

    WebUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:custom.api}-web
        GenerateSecret: false
        UserPoolId: { Ref: CognitoUserPoolUsers }

    AuthRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.api}-auth
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Federated: cognito-identity.amazonaws.com
              Action: sts:AssumeRoleWithWebIdentity
              Condition:
                ForAnyValue:StringLike:
                  "cognito-identity.amazon.com:amr": "authenticated"
        Policies:
          - PolicyName: AllowProfilePictureDownload
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Action:
                    - "s3:GetObject"
                  Effect: Allow
                  Resource:
                    - { Fn::GetAtt: [ FileStorage, Arn ]}
                    - { Fn::Join: [ "/", [{ Fn::GetAtt: [ FileStorage, Arn ]}, "*" ]]}
          - PolicyName: AllowProfilePictureUpload
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Action:
                    - "s3:PutObject"
                  Effect: Allow
                  Resource:
                    - { Fn::Join: [ "/", [{ Fn::GetAtt: [ FileStorage, Arn ]}, "profilePictures/*" ]]}
          - PolicyName: AllowAuthenticatedAppSyncAccess
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Action:
                    - "appsync:GraphQL"
                  Effect: Allow
                  Resource:
                    - { Fn::Join: [ "/", [{ Fn::GetAtt: [ GraphQlApi, Arn ]}, "*" ]]}

    UnauthRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.api}-unauth
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Federated: cognito-identity.amazonaws.com
              Action: sts:AssumeRoleWithWebIdentity
              Condition:
                ForAnyValue:StringLike:
                  "cognito-identity.amazon.com:amr": "unauthenticated"
        Policies:
          - PolicyName: AllowProfilePictureDownload
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Action:
                    - "s3:GetObject"
                  Effect: Allow
                  Resource:
                    - { Fn::GetAtt: [ FileStorage, Arn ]}
                    - { Fn::Join: [ "/", [{ Fn::GetAtt: [ FileStorage, Arn ]}, "*" ]]}
          - PolicyName: AllowUnauthenticatedAppSyncQueries
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Action:
                    - "appsync:GraphQL"
                  Effect: Allow
                  Resource:
                    - { Fn::Join: [ "/", [{ Fn::GetAtt: [ GraphQlApi, Arn ]}, "types/Query/*" ]]}

    IdentityPool:
      Type: AWS::Cognito::IdentityPool
      Properties:
        IdentityPoolName: ${self:custom.api}
        AllowUnauthenticatedIdentities: true
        CognitoIdentityProviders:
          - ClientId: { Ref: ReactNativeUserPoolClient }
            ProviderName: { Fn::Sub: [ 'cognito-idp.${self:provider.region}.amazonaws.com/#{client}', { "client": { Ref: CognitoUserPoolUsers }}]}
          - ClientId: { Ref: WebUserPoolClient }
            ProviderName: { Fn::Sub: [ 'cognito-idp.${self:provider.region}.amazonaws.com/#{client}', { "client": { Ref: CognitoUserPoolUsers }}]}

    IdentityPoolRoleMap:
      Type: AWS::Cognito::IdentityPoolRoleAttachment
      Properties:
        IdentityPoolId: { Ref: IdentityPool }
        Roles:
          unauthenticated: { Fn::GetAtt: [ UnauthRole, Arn ]}
          authenticated: { Fn::GetAtt: [ AuthRole, Arn ]}

    # -------------------------------------------------------------------------
    # END: AUTHENTICATION
    # -------------------------------------------------------------------------

    # -------------------------------------------------------------------------
    # BEGIN: DATA STORAGE
    # -------------------------------------------------------------------------
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.api}
        KeySchema:
          - AttributeName: typeName
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: typeName
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.ddb_readIOPS}
          WriteCapacityUnits: ${self:custom.ddb_writeIOPS}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    ElasticSearchDomain:
      Type: AWS::Elasticsearch::Domain
      Properties:
        DomainName: ${self:custom.es_domain}
        ElasticsearchVersion: "6.2"
        ElasticsearchClusterConfig:
          ZoneAwarenessEnabled: false
          InstanceCount: ${self:custom.es_instanceCount}
          InstanceType: ${self:custom.es_instanceType}
        EBSOptions:
          EBSEnabled: true
          VolumeType: "gp2"
          VolumeSize: ${self:custom.es_ebsVolumeGB}

    FileStorage:
      Type: AWS::S3::Bucket
      Properties:
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
              MaxAge: 3000

    # -------------------------------------------------------------------------
    # END: DATA STORAGE
    # -------------------------------------------------------------------------

    # -------------------------------------------------------------------------
    # BEGIN: PERMISSIONS
    # -------------------------------------------------------------------------

    ElasticSearchStreamingLambdaIAMRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.api}-ESStreamingLambdaRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: "lambda.amazonaws.com"
              Action: "sts:AssumeRole"
        Policies:
          - PolicyName: ElasticSearchAccess
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Action:
                    - "es:ESHttpPost"
                    - "es:ESHttpPut"
                    - "es:ESHttpGet"
                  Effect: Allow
                  Resource:
                    - { Fn::Join: [ "", [{ Fn::GetAtt: [ ElasticSearchDomain, DomainArn ]}, "/*" ]]}
          - PolicyName: DynamoDBStreamAccess
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Action:
                    - "dynamodb:DescribeStream"
                    - "dynamodb:GetRecords"
                    - "dynamodb:GetShardIterator"
                    - "dynamodb:ListStreams"
                  Effect: Allow
                  Resource:
                    - { Fn::GetAtt: [ DynamoDBTable, StreamArn ]}
          - PolicyName: CloudWatchLogsAccess
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Action:
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                  Effect: Allow
                  Resource:
                    - "arn:aws:logs:#{AWS::Region}:#{AWS::AccountId}:*"

    AWSAppSyncS3LambdaIAMRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.api}-AWSAppSyncS3LambdaIAMRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: "lambda.amazonaws.com"
              Action: "sts:AssumeRole"
        Policies:
          - PolicyName: S3Access
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Action:
                    - "s3:GetObject"
                  Effect: Allow
                  Resource:
                    - { Fn::GetAtt: [ FileStorage, Arn ]}
                    - { Fn::Join: [ "/", [{ Fn::GetAtt: [ FileStorage, Arn ]}, "*" ]]}
          - PolicyName: CloudWatchLogsAccess
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Action:
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                  Effect: Allow
                  Resource:
                    - "arn:aws:logs:#{AWS::Region}:#{AWS::AccountId}:*"

    AppSyncLoggingServiceRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.api}-AppSyncLoggingServiceRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: "appsync.amazonaws.com"
              Action: "sts:AssumeRole"
        Policies:
          - PolicyName: CloudWatchLogsAccess
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Action:
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                  Effect: Allow
                  Resource:
                    - "arn:aws:logs:#{AWS::Region}:#{AWS::AccountId}:*"

    # -------------------------------------------------------------------------
    # END: PERMISSIONS
    # -------------------------------------------------------------------------
